datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/clever_lab_task_10
  username: root
  password: root
cache:
  algorithm: lru
  capacity: 10
liquibase:
  enabled: true
  changelog: changelog-master.xml